#!/usr/bin/env bash
# post-test.sh — Provana Azure DevOps CI gate
# provana-superpowers v5.1.0
#
# Runs after pytest. Blocks merge unless:
#   - All tests pass
#   - No Critical or Important code review issues remain open
#   - PM/QA verdict from agent-qc-harness is PASS or CONDITIONAL PASS
#
# Invoked by Azure DevOps pipeline as a gate step before PR merge.
# Can also be run locally before requesting review.
#
# Exit 0 = gate PASS, merge allowed
# Exit 1 = gate FAIL, merge blocked

set -euo pipefail

GATE_PASS=true
GATE_REPORT=()

echo "=== Provana CI gate (post-test) ==="
echo "Date: $(date -u '+%Y-%m-%d %H:%M UTC')"
echo ""

# ── 1. Test results ───────────────────────────────────────────────────────────
echo "[1/4] Test suite..."

TEST_RESULTS_FILE="${PYTEST_RESULTS:-reports/test-results.xml}"
PYTEST_EXIT="${PYTEST_EXIT_CODE:-}"

if [ -n "$PYTEST_EXIT" ]; then
  if [ "$PYTEST_EXIT" -ne 0 ]; then
    GATE_REPORT+=("❌ FAIL: Test suite — pytest exited with code $PYTEST_EXIT")
    GATE_PASS=false
  else
    GATE_REPORT+=("✅ PASS: Test suite")
  fi
elif command -v pytest &>/dev/null; then
  if pytest tests/ -q --tb=no 2>/dev/null; then
    GATE_REPORT+=("✅ PASS: Test suite")
  else
    GATE_REPORT+=("❌ FAIL: Test suite — run 'pytest tests/ -v' for details")
    GATE_PASS=false
  fi
else
  GATE_REPORT+=("⚠️  SKIP: pytest not found")
fi

# ── 2. Code review gate ───────────────────────────────────────────────────────
echo "[2/4] Code review status..."

# Look for latest review file
REVIEW_DIR="reviews"
if [ -d "$REVIEW_DIR" ]; then
  LATEST_REVIEW=$(ls -t "$REVIEW_DIR"/review-*.md 2>/dev/null | head -1 || true)

  if [ -n "$LATEST_REVIEW" ]; then
    # Check for open Critical issues
    if grep -q "BLOCK\|Critical.*[^✅]" "$LATEST_REVIEW" 2>/dev/null; then
      if ! grep -q "\[x\] APPROVE" "$LATEST_REVIEW" 2>/dev/null; then
        GATE_REPORT+=("❌ FAIL: Code review — Critical or BLOCK verdict found in $LATEST_REVIEW")
        GATE_PASS=false
      else
        GATE_REPORT+=("✅ PASS: Code review — APPROVE verdict")
      fi
    elif grep -q "\[x\] APPROVE" "$LATEST_REVIEW" 2>/dev/null; then
      GATE_REPORT+=("✅ PASS: Code review — APPROVE verdict")
    elif grep -q "\[x\] REQUEST CHANGES" "$LATEST_REVIEW" 2>/dev/null; then
      GATE_REPORT+=("❌ FAIL: Code review — REQUEST CHANGES pending")
      GATE_PASS=false
    else
      GATE_REPORT+=("⚠️  WARN: Code review — verdict not found in $LATEST_REVIEW")
    fi
  else
    GATE_REPORT+=("⚠️  WARN: No review file found in $REVIEW_DIR/ — run requesting-provana-review first")
  fi
else
  GATE_REPORT+=("⚠️  WARN: No reviews/ directory — run requesting-provana-review before merging")
fi

# ── 3. QC harness verdict ─────────────────────────────────────────────────────
echo "[3/4] PM/QA verdict (agent-qc-harness)..."

QC_REPORT_DIR="reports"
if [ -d "$QC_REPORT_DIR" ]; then
  # Look for most recent QC report
  LATEST_QC=$(ls -t "$QC_REPORT_DIR"/qc-report-*.md 2>/dev/null | head -1 || \
              ls -t "$QC_REPORT_DIR"/*-qc-*.md 2>/dev/null | head -1 || true)

  if [ -n "$LATEST_QC" ]; then
    if grep -q "\[x\] PASS\|PM/QA verdict.*PASS\|CONDITIONAL PASS" "$LATEST_QC" 2>/dev/null; then
      GATE_REPORT+=("✅ PASS: PM/QA verdict — $(grep -oE 'PASS|CONDITIONAL PASS' "$LATEST_QC" | head -1)")
    elif grep -q "\[x\] FAIL\|PM/QA verdict.*FAIL" "$LATEST_QC" 2>/dev/null; then
      GATE_REPORT+=("❌ FAIL: PM/QA verdict — FAIL found in $LATEST_QC")
      GATE_PASS=false
    else
      GATE_REPORT+=("⚠️  WARN: QC report found but verdict unclear — check $LATEST_QC")
    fi
  else
    GATE_REPORT+=("⚠️  WARN: No QC report found — run agent-qc-harness before merging")
  fi
else
  GATE_REPORT+=("⚠️  WARN: No reports/ directory — run agent-qc-harness before merging")
fi

# ── 4. Hallucination detector ─────────────────────────────────────────────────
echo "[4/4] Hallucination check..."

HALLUCINATION_REPORT=$(ls -t reports/hallucination-*.md 2>/dev/null | head -1 || true)
if [ -n "$HALLUCINATION_REPORT" ]; then
  if grep -q "verdict.*FAIL\|HALLUCINATION.*FAIL" "$HALLUCINATION_REPORT" 2>/dev/null; then
    GATE_REPORT+=("❌ FAIL: Hallucination detector — FAIL in $HALLUCINATION_REPORT")
    GATE_PASS=false
  else
    GATE_REPORT+=("✅ PASS: Hallucination detector")
  fi
else
  GATE_REPORT+=("⏭  SKIP: No hallucination report — will be generated by agent-qc-harness")
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "=== CI Gate Report ==="
for item in "${GATE_REPORT[@]}"; do
  echo "  $item"
done
echo ""

if [ "$GATE_PASS" = true ]; then
  echo "✅ CI GATE: PASS — merge allowed"
  exit 0
else
  echo "❌ CI GATE: FAIL — merge BLOCKED"
  echo ""
  echo "Fix the failing items above before requesting merge."
  exit 1
fi
